name: Cypress Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            # - name: Start the application
            #   run: npm run dev &
            #   env:
            #     CI: true

            - name: Run Cypress tests with Chrome
              run: npx cypress run --browser chrome
              env:
                  CI: true
